/* ── Status overlays — backend wake-up banner, error toasts, fallback badge ── */
"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Loader2, X, Info } from "lucide-react";
import { useTrafficStore } from "@/lib/store";
import { api } from "@/lib/api";
import { cn } from "@/lib/utils";
import type { OutputSource } from "@/lib/types";

/* Free-tier backends sleep after 15 min idle and take about a minute to wake */
const SHOW_AFTER_MS = 2500;
const EXPECTED_WAKE_S = 60;

export function BackendStatusBanner() {
  const connected = useTrafficStore((s) => s.connected);
  const disconnectedSince = useTrafficStore((s) => s.disconnectedSince);
  const [now, setNow] = useState(() => Date.now());

  // Nudge a sleeping backend awake as soon as the dashboard opens
  useEffect(() => {
    api.health().catch(() => {});
  }, []);

  useEffect(() => {
    if (connected) return;
    const t = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(t);
  }, [connected]);

  if (connected || !disconnectedSince || now - disconnectedSince < SHOW_AFTER_MS) return null;

  const waited = Math.floor((now - disconnectedSince) / 1000);
  const slow = waited > EXPECTED_WAKE_S + 30;

  return (
    <div
      role="status"
      className={cn(
        "flex items-center gap-2 px-4 py-2 text-xs border-b",
        slow ? "bg-red-50 text-red-800 border-red-200" : "bg-amber-50 text-amber-900 border-amber-200"
      )}
    >
      {slow ? <AlertTriangle className="w-3.5 h-3.5 shrink-0" /> : <Loader2 className="w-3.5 h-3.5 shrink-0 animate-spin" />}
      <span>
        {slow
          ? `Still can't reach the backend after ${waited}s. It may be down — retrying every 10s.`
          : `Starting the server (free hosting sleeps when idle) — usually about ${EXPECTED_WAKE_S}s. Waiting ${waited}s…`}
      </span>
    </div>
  );
}

export function Toaster() {
  const toasts = useTrafficStore((s) => s.toasts);
  const dismiss = useTrafficStore((s) => s.dismissToast);
  if (!toasts.length) return null;

  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 max-w-[calc(100vw-2rem)] w-80" aria-live="polite">
      {toasts.map((t) => (
        <div
          key={t.id}
          className={cn(
            "flex items-start gap-2 rounded-lg border px-3 py-2 text-xs shadow-lg bg-white",
            t.kind === "error" ? "border-red-200" : "border-blue-200"
          )}
        >
          {t.kind === "error"
            ? <AlertTriangle className="w-3.5 h-3.5 mt-0.5 text-danger shrink-0" />
            : <Info className="w-3.5 h-3.5 mt-0.5 text-primary shrink-0" />}
          <p className="flex-1 text-foreground leading-relaxed">{t.message}</p>
          <button onClick={() => dismiss(t.id)} aria-label="Dismiss" className="text-muted hover:text-foreground">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      ))}
    </div>
  );
}

/** Shown in a results tab while the agent pipeline is still running. */
export function AgentsWorking({ what }: { what: string }) {
  return (
    <div className="flex flex-col items-center justify-center h-full text-muted py-12" role="status">
      <Loader2 className="w-8 h-8 mb-3 text-primary animate-spin" />
      <p className="text-sm font-medium text-foreground">Agents are working…</p>
      <p className="text-xs mt-1">{what} will appear here in a few seconds</p>
    </div>
  );
}

/** Marks output produced by rule-based fallback because the LLM call failed. */
export function FallbackBadge({ source, className }: { source?: OutputSource; className?: string }) {
  if (source !== "fallback") return null;
  return (
    <span
      title="The AI model was unavailable, so this was generated by simple rules from sensor data."
      className={cn(
        "inline-flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 border border-slate-200",
        className
      )}
    >
      <AlertTriangle className="w-2.5 h-2.5" />
      Rule-based fallback
    </span>
  );
}
